services:
  reach-ui:
    # tty: true
    stdin_open: true
    ports:
      - 3000:3000
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - type: volume
        source: nodemodules
        target: /app/node_modules
        volume:
          nocopy: true
      - type: volume
        source: npm
        target: /root/.npm
        volume:
          nocopy: true
    # depends_on:
    #   - reach-ui-ngrok
    environment:
      APP_ENV: development
      NODE_ENV: development
      REACT_APP_GOOGLE_FONTS_API_KEY: AIzaSyAcOaBLg0elTORAXH5tPHuqqiNQTrCCDY4

  # reach-ui-ngrok:
  #   image: public.ecr.aws/bowtie/ngrok
  #   env_file:
  #     - .env.ngrok
  #   environment:
  #     NGROK_PROTOCOL: http
  #     NGROK_PORT: 3000
  #     NGROK_TARGET: reach-ui

volumes:
  npm:
  nodemodules:
